### ISSUE TITLE
I press Ctrl+C the program return many error, but it does copy, it does copy many times

### ISSUE THREAD

**Issue by rgw5267** [joshburnett/addcopyfighandler#17]
I only `import addcopyfighandler` in the program，and press Ctrl + C

![recording](https://github.com/joshburnett/addcopyfighandler/assets/1254990/919e17f4-dcfa-4e20-92ec-9df6e6c3f30b)
```
Figure copied.
Figure copied.
Figure copied.
Figure copied.
Figure copied.
Figure copied.
Figure copied.
Traceback (most recent call last):
  File "matplotlib\cbook.py", line 298, in process
  File "addcopyfighandler.py", line 271, in clipboard_handler
  File "addcopyfighandler.py", line 108, in copyfig
AttributeError: No figure found!
Traceback (most recent call last):
  File "matplotlib\cbook.py", line 298, in process
  File "addcopyfighandler.py", line 271, in clipboard_handler
  File "addcopyfighandler.py", line 108, in copyfig
AttributeError: No figure found!
```

**Comment by rgw5267** [comment]
I created a Pull Request #18 for this issue

**Comment by joshburnett** [comment]
Thanks for the PR. Accepted!
